/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bfbc_toys_fastlimitset_Painter */

#ifndef _Included_bfbc_toys_fastlimitset_Painter
#define _Included_bfbc_toys_fastlimitset_Painter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bfbc_toys_fastlimitset_Painter
 * Method:    fillArray
 * Signature: (II[I)V
 */
JNIEXPORT void JNICALL Java_bfbc_toys_fastlimitset_Painter_fillArray
  (JNIEnv *, jclass, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
